# Generated by Django 5.2 on 2025-05-15 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partit',
            name='gols_local',
        ),
        migrations.RemoveField(
            model_name='partit',
            name='gols_visitant',
        ),
    ]
