# Generated by Django 5.2 on 2025-05-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0002_remove_partit_gols_local_remove_partit_gols_visitant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lliga',
            name='data_fi',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='lliga',
            name='data_inici',
            field=models.DateField(null=True),
        ),
    ]
